// <auto-generated />
using BancoCunha.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BancoCunha.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20210916013437_Inicial01")]
    partial class Inicial01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BancoCunha.Models.Banco", b =>
                {
                    b.Property<int>("Idbanco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Codbanco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nomebanco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Idbanco");

                    b.ToTable("Banco");
                });
#pragma warning restore 612, 618
        }
    }
}
